services:
    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ims_chat_app
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app-network

    php:
        image: php:8.2-fpm
        container_name: php
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root_password
        networks:
            - app-network

    reverb:
        build:
            context: .
            dockerfile: reverb/Dockerfile
        container_name: reverb
        ports:
            - "8080:8080"
#            - "6001:6001"
        volumes:
            - app-data:/var/www/html
        working_dir: /var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    app-data:
        driver: local
